; PlatformIO Project Configuration File for Full Voice AI Assistant
;
;   INMP441 Microphone (STT) + Google Gemini AI + MAX98357A Speaker (TTS)

[env:4d_systems_esp32s3_gen4_r8n16]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
monitor_echo = yes
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/earlephilhower/BackgroundAudio.git
    https://github.com/jobitjoseph/WitAITTS.git
