; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
build_flags =
    -DCORE_DEBUG_LEVEL=2
    -DBOARD_HAS_PSRAM
lib_deps =
    https://github.com/schreibfaul1/ESP32-audioI2S.git
    bblanchon/ArduinoJson@^7.2.2
